/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vocabulary;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.FileReader;
import java.util.LinkedList;
import java.util.Random;
import java.util.StringTokenizer;
import javax.swing.JOptionPane;

/**
 *
 * @author ahhun
 */
public class Main extends javax.swing.JFrame {
    private LinkedList<Vocabulary> vocab = new LinkedList();
    private Vocabulary vocabulary;
    private boolean isCheck = false;
    int mistake = 0;
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.setSize(1000, this.getHeight());
        loadFile();
        lbQuestion.setText("Question(s): " + vocab.size());
    }
    
    private void loadFile() {
        try {
            FileReader fr = new FileReader("kanji_lesson.txt");
            BufferedReader br = new BufferedReader(fr);
            String tmp;
            while ((tmp = br.readLine()) != null) {
                StringTokenizer stk = new StringTokenizer(tmp, ",");
                String question = stk.nextToken();
                String answer = stk.nextToken();
                vocab.add(new Vocabulary(answer, question));
            }
            br.close();
            fr.close();
        } catch (Exception ex) {}
        
//        try (InputStream bytes = new FileInputStream("kanji_lesson7.txt")) {
//            /* See how I'm specifying the UTF-8 encoding explicitly? */
//            Reader chars = new InputStreamReader(bytes, StandardCharsets.UTF_8);
//            BufferedReader lines = new BufferedReader(chars);
//            while (true) {
//                String line = lines.readLine();
//                if (line == null) {
//                    break;
//                }
//                StringTokenizer stk = new StringTokenizer(line, ",");
//                String vietNam = stk.nextToken();
//                String nihon = stk.nextToken();
//                vocab.add(new Vocabulary(nihon, vietNam));
//            }
//            lines.close();
//            chars.close();
//            bytes.close();
//        } catch (Exception ex) {
//        }
    }
    
    private void getQuestion() {
        if (vocab.isEmpty()) {
            JOptionPane.showMessageDialog(this, "You have completed the game!\n" +
                    "Good luck!");
            System.exit(0);
        }
        int rd = new Random().nextInt(vocab.size());
        vocabulary = vocab.get(rd);
        lbVocabulary.setText(vocabulary.getQuestion());
        lbMessage.setText("You have made " + vocabulary.getMistakes() + " mistake(s) on this word!");
        txtAnswer.setText("");
        txtAnswer.setBackground(Color.WHITE);
        lbQuestion.setText("Question(s): " + vocab.size());
        isCheck = true;
        btnCheck.setText("Check");
    }
    
    private void checkAnswer() {
        String nihon = txtAnswer.getText().trim();
        vocab.remove(vocabulary);
        if (nihon.equalsIgnoreCase(vocabulary.getAnswer()))
            txtAnswer.setBackground(new Color(178, 255, 89));
        else {
            txtAnswer.setBackground(new Color(255, 82, 82));
            txtAnswer.setText(nihon + " -> " + vocabulary.getAnswer());
            mistake++;
            vocabulary.makeMistake();
            lbMistake.setText("Mistake(s): " + mistake);
            vocab.add(vocabulary);
        }
        isCheck = false;
        btnCheck.setText("Next");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbVocabulary = new javax.swing.JLabel();
        txtAnswer = new javax.swing.JTextField();
        btnCheck = new javax.swing.JButton();
        lbMistake = new javax.swing.JLabel();
        lbQuestion = new javax.swing.JLabel();
        lbMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbVocabulary.setFont(new java.awt.Font("Yu Gothic", 1, 60)); // NOI18N
        lbVocabulary.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbVocabulary.setText("Vocabulary");

        txtAnswer.setFont(new java.awt.Font("Yu Gothic", 0, 24)); // NOI18N
        txtAnswer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAnswerKeyReleased(evt);
            }
        });

        btnCheck.setBackground(new java.awt.Color(118, 255, 3));
        btnCheck.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnCheck.setText("Start (Enter)");
        btnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckActionPerformed(evt);
            }
        });

        lbMistake.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbMistake.setForeground(new java.awt.Color(244, 67, 54));
        lbMistake.setText("Mistake(s): 0");

        lbQuestion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbQuestion.setForeground(new java.awt.Color(33, 150, 243));
        lbQuestion.setText("Question(s): 0");

        lbMessage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbMessage.setForeground(new java.awt.Color(236, 64, 122));
        lbMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMessage.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAnswer)
                    .addComponent(lbVocabulary, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                    .addComponent(btnCheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbMistake)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbQuestion))
                    .addComponent(lbMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbMessage)
                .addGap(3, 3, 3)
                .addComponent(lbVocabulary)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMistake)
                    .addComponent(lbQuestion))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckActionPerformed
        if (isCheck) checkAnswer();
        else getQuestion();
    }//GEN-LAST:event_btnCheckActionPerformed

    private void txtAnswerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAnswerKeyReleased
        char key = evt.getKeyChar();
        if (key == '\n')
            if (isCheck) checkAnswer();
            else getQuestion();
    }//GEN-LAST:event_txtAnswerKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheck;
    private javax.swing.JLabel lbMessage;
    private javax.swing.JLabel lbMistake;
    private javax.swing.JLabel lbQuestion;
    private javax.swing.JLabel lbVocabulary;
    private javax.swing.JTextField txtAnswer;
    // End of variables declaration//GEN-END:variables
}
